version: '3'
services:
#   project_name: PAD_ANOMA
  docker-influxdb-grafana:
    image : philhawthorne/docker-influxdb-grafana:latest
    environment:
      - TZ=Asia/Seoul
    ports:
      - ${GRAFANA_PORT}:3003
      - ${CHRONO_PORT}:8083
      - ${INFLUX_DB_PORT}:8086
    container_name: docker-influxdb-grafana
    
    volumes:
        - $PWD/anoma_influx_db:/var/lib/influxdb
        - $PWD/anoma_grafana:/var/lib/grafana
