---
- apiVersion: v1
  kind: Template
  labels:
    application: ${APPLICATION_NAME}
  metadata:
    name: mlflow-experiment-job

  parameters:
    - description: Application name
      from: "experiment-run"
      generate: expression
      name: APPLICATION_NAME
      required: true
    - name: MLFLOW_TRACKING_URI
      value: http://$(MLFLOW_SERVER_SERVICE_SERVICE_HOST):$(MLFLOW_SERVER_SERVICE_SERVICE_PORT)
      required: true
      # To use the internal host and port number to connect to the mlflow tracking server
      description: "URI to the MLFlow server. Only required if the MLFlow server is in another Namespace"
    - name: LIMIT_CPU
      value: "2"
      description: "Limit number of CPUs allocated to the job"
      required: false
    - name: LIMIT_MEM
      value: "2G"
      description: "Limit amount of memory allocated to the job"
      required: false
    - name: REQUEST_CPU
      value: "1"
      description: "Requested number of CPUs allocated to the job"
      required: false
    - name: REQUEST_MEM
      value: "1G"
      description: "Requested amount of memory allocated to the job"
      required: false
    - name: FLT_PROM_URL
      description: "URL for the Prometheus Host from where the metric data will be collected"
      required: true
    - name: FLT_PROM_ACCESS_TOKEN
      description: "OAuth Token used while communicating with the Prometheus Host"
      required: false
    - name: FLT_METRICS_LIST
      description: "List of metrics separated by a ';', on which the model will be trained on"
      required: true
    - name: FLT_RETRAINING_INTERVAL_MINUTES
      description: "The duration of metric data that is collected and added to the training data every epoch"
      value: "60"
      required: true
    - name: FLT_ROLLING_TRAINING_WINDOW_SIZE
      description: "a rolling data window on which the model will be trained"
      value: "2d"
      required: true
    - name: FLT_DEBUG_MODE
      description: "Enable Verbose logging"
      value: "False"
      required: false
    - name: APP_FILE
      description: "python application file name that will be run"
      value: "test_model.py"
      required: true
    - name: NB_USER
      description: "Name of user that will be logged in mlflow"
      value: "unknown"
      required: true
    - name: FLT_DATA_START_TIME
      description: "w"
      value: "3d"
      required: true
    - name: FLT_DATA_END_TIME
      description: "w"
      value: "now"
      required: true
    - name: FLT_TRUE_ANOMALY_THRESHOLD
      description: "threshold value to calculate true anomalies using a linear function"
      value: "0.001"
      required: true
    - name: OC_APP_IMAGE_NAME
      description: "Name of the application image to be pulled from the registry"
      value: "prometheus-anomaly-detector-prophet-image"
      required: true

  objects:
    - apiVersion: batch/v1
      kind: Job
      metadata:
        name: ${APPLICATION_NAME}
        labels:
          app: ${APPLICATION_NAME}
          experiment: ${OC_APP_IMAGE_NAME}
      spec:
        template:
          metadata:
            name: ${APPLICATION_NAME}
          spec:
            containers:
              - name: ${APPLICATION_NAME}
                image: ${OC_APP_IMAGE_NAME}
                imagePullPolicy: Always
                resources:
                  requests:
                    memory: ${REQUEST_MEM}
                    cpu: ${REQUEST_CPU}
                  limits:
                    memory: ${LIMIT_MEM}
                    cpu: ${LIMIT_CPU}
                env:
                  - name: NB_USER
                    value: ${NB_USER}
                  - name: APP_FILE
                    value: ${APP_FILE}
                  - name: MLFLOW_TRACKING_URI
                    value: ${MLFLOW_TRACKING_URI}
                  - name: FLT_PROM_URL
                    value: ${FLT_PROM_URL}
                  - name: FLT_PROM_ACCESS_TOKEN
                    value: ${FLT_PROM_ACCESS_TOKEN}
                  - name: FLT_METRICS_LIST
                    value: ${FLT_METRICS_LIST}
                  - name: FLT_DATA_START_TIME
                    value: ${FLT_DATA_START_TIME}
                  - name: FLT_DATA_END_TIME
                    value: ${FLT_DATA_END_TIME}
                  - name: FLT_ROLLING_TRAINING_WINDOW_SIZE
                    value: ${FLT_ROLLING_TRAINING_WINDOW_SIZE}
                  - name: FLT_RETRAINING_INTERVAL_MINUTES
                    value: ${FLT_RETRAINING_INTERVAL_MINUTES}
                  - name: FLT_TRUE_ANOMALY_THRESHOLD
                    value: ${FLT_TRUE_ANOMALY_THRESHOLD}
                  - name: FLT_DEBUG_MODE
                    value: ${FLT_DEBUG_MODE}
            restartPolicy: OnFailure
