version: '3'
services:
#   project_name: PAD_ANOMA
  anoma:
#     image : quay.io/aicoe/prometheus-anomaly-detector:latest
    image : pad_anoma:latest
#     stdin_open: true
#     tty: true
#     image : quay.io/4n4nd/prometheus-anomaly-detector:latest
    user : nobody
    environment:
      - TZ=Asia/Seoul
#       - COMPOSE_PROJECT_NAME=PAD_ANOMA
      - APP_FILE=app.py
      - FLT_PROM_URL=http://${ANOMA_IP}:${PROMETHEUS_PORT}
      - FLT_RETRAINING_INTERVAL_MINUTES=20
#       - FLT_METRICS_LIST=another_metric{exported_instance='some_instance',exported_job='some_job',instance='${PUSH_GATE_WAY_IP}',job='some_job'};
#                         some_metric{exported_instance='some_instance',exported_job='some_job',instance='${PUSH_GATE_WAY_IP}',job='some_job',label='val1'} # set metrics
      - FLT_METRICS_LIST=another_metric{exported_instance='some_instance',exported_job='some_job',instance='some_instance',job='some_job'};
                        some_metric{exported_instance='some_instance',exported_job='some_job',instance='some_instance',job='some_job',label='val1'} # set metrics

      - FLT_ROLLING_TRAINING_WINDOW_SIZE=1h
    ports:
      - ${ANOMA_PAD_PORT}:8080
    container_name: PAD_ANOMA
    
    volumes:
        - $PWD:/PAD
    command:
        - bash
        - -c
        - python app.py --model_name model # set model python file name



# python /PAD/${APP_FILE}

