version: '3'
services:
#   project_name: PAD_ANOMA
  anoma:
#     image : quay.io/aicoe/prometheus-anomaly-detector:latest
    image : mad_anoma:latest
    privileged: true 
#     stdin_open: true
#     tty: true
#     image : quay.io/4n4nd/prometheus-anomaly-detector:latest
    user : nobody
    environment:
#       - TZ=Asia/Seoul
#       - COMPOSE_PROJECT_NAME=PAD_ANOMA
      - APP_FILE=train_app.py
      - FLT_INFL_URL=${ANOMA_IP}
      - FLT_RETRAINING_INTERVAL_MINUTES=15
      - FLT_ROLLING_TRAINING_WINDOW_SIZE=1h
      - FLT_DATABASE_NAME=prometheus
      - FLT_DATABASE_PORT=${INFLUX_DB_PORT}
      - FLT_DATABASE_USERNAME=${INFL_DATABASE_USERNAME}
      - FLT_DATABASE_PASSWORD=${INFL_DATABASE_PASSWORD}
      - FLT_TABLE_LIST=some_metric # set metrics
#       - FLT_ALL_METRICS=True
      - MODEL_DIR=model
#       - FLT_DEBUG_MODE=True
    ports:
      - ${ANOMA_PAD_PORT}:8080
    container_name: MAD_ANOMA
    
    volumes:
        - $PWD:/PAD
    command:
        - bash
        - -c
        - python train_app.py --model_name model_lstmvae # set model python file name



# python /PAD/${APP_FILE}

