version: '3'
services:
  anoma:
    image : mad_anoma:latest
    privileged: true 
    user : nobody
    environment:
#       - TZ=Asia/Seoul
      - FLT_INFL_URL=${ANOMA_IP}
      - FLT_RETRAINING_INTERVAL_MINUTES=15
      - FLT_ROLLING_TRAINING_WINDOW_SIZE=1h
      - FLT_DATABASE_NAME=prometheus
      - FLT_DATABASE_PORT=${INFLUX_DB_PORT}
      - FLT_DATABASE_USERNAME=${INFL_DATABASE_USERNAME}
      - FLT_DATABASE_PASSWORD=${INFL_DATABASE_PASSWORD}
      - FLT_TABLE_LIST=some_metric # set table
#       - FLT_COLUMN_LIST={'some_metric':['val1', 'val2'],'ano_metric':['val11', 'val22']} # set column
#       - FLT_ALL_TABLES=True
      - FLT_ALL_COLUMNS=True
      - MODEL_DIR=model
#       - FLT_DEBUG_MODE=True
    container_name: MAD_ANOMA
    
    volumes:
        - $PWD:/PAD
    command:
        - bash
        - -c
        - python train_app.py --model_name model_lstmvae # set model python file name



# python /PAD/${APP_FILE}

